backend:
  name: github
  repo: samuel-ping/personal-website-v3
  branch: main
  base_url: https://samuelping.glitch.me

media_folder: "public/uploads/images/"
public_folder: "uploads/images/"

site_url: https://samuel-ping.github.io/personal-website-v3

collections:
  - name: "about-me"
    label: "About Me"
    description: "My about me blurb. Introduces me to the reader."
    file: "src/content/about-me.md"
    fields:
      - { label: "Description", name: "description", widget: "text" }

  - name: "resume"
    label: "Resume"
    description: "My latest resume, in PDF form."
    folder: "public/uploads"
    widget: "file"
    media_library:
      config:
        multiple: false

  - name: "projects"
    label: "Projects"
    description: "My personal projects!"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "projects",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Timeframe", name: "timeframe", widget: "string" }
      - { label: "Technologies Used", name: "technologies", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }
