backend:
  name: test-repo
  repo: samuel-ping/personal-website-v3
  branch: main
  base_url: https://samuelping.glitch.me

media_folder: "public/uploads/images/"
public_folder: "uploads/images/"

site_url: https://samuel-ping.github.io/personal-website-v3

collections:
  - name: "personal-information"
    label: "Personal Information"
    files:
      - name: "about-me"
        label: "About Me"
        file: "src/content/about-me.md"
        fields:
          - { label: "Description", name: "description", widget: "markdown" }
      - name: "resume"
        label: "Resume"
        file: "public/uploads/08062020_Ping_Samuel.pdf"
        fields:
          - { label: "Resume", name: "resume", widget: "file" }
      - name: "contact-information"
        label: "Contact Information"
        file: "src/content/contact-information.md"
        fields:
          - {
              label: "GitHub Profile URL",
              name: "github-url",
              widget: "string",
            }
          - {
              label: "LinkedIn Profile URL",
              name: "linkedin-url",
              widget: "string",
            }
          - { label: "Email Address", name: "email-address", widget: "string" }

  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Timeframe", name: "timeframe", widget: "string" }
      - { label: "Repository URL", name: "repo-url", widget: "string" }
      - { label: "Live Website URL", name: "website-url", widget: "string" }
      - { label: "Technologies Used", name: "technologies", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
