backend:
  name: github
  # name: test-repo
  repo: samuel-ping/personal-website-v3
  branch: main
  base_url: https://samuelping.herokuapp.com/

media_folder: "client/public/uploads/"
public_folder: "uploads/"

site_url: https://samuel-ping.github.io/personal-website-v3

collections:
  - name: "taglines"
    label: "Taglines"
    label_singular: "Tagline"
    description: "The taglines that go on the landing page!"
    folder: "client/src/content/home"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Job Title", name: "job-title", widget: "string" }
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Company Website URL", name: "website-url", widget: "string" }
  - name: "about"
    label: "About Me"
    description: "My about me blurb!"
    files:
      - name: "profile-picture"
        label: "Profile Picture"
        file: "client/public/uploads/profile.jpg"

      - name: "about-description"
        label: "About Me Description"
        file: "client/src/content/about/about-me.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "contact"
    label: "Contact Information"
    description: "My contact information!"
    files:
      - name: "resume"
        label: "Resume"
        fields:
          - {
              label: "Resume",
              name: "resume",
              widget: "file",
              default: "client/public/uploads/Ping_Samuel-Resume.pdf",
            }
          - {
              label: "Upload Date",
              name: "date",
              widget: "datetime",
              date_format: "MM-DD-YYYY",
              time_format: false,
              picker_utc: true,
              hint: "Date this resume was last updated.",
            }
      - name: "links"
        label: "Links"
        file: "client/src/content/contact/links.md"
        fields:
          - {
              label: "GitHub Profile URL",
              name: "github-url",
              widget: "string",
            }
          - {
              label: "LinkedIn Profile URL",
              name: "linkedin-url",
              widget: "string",
            }
          - { label: "Email Address", name: "email-address", widget: "string" }
  - name: "work"
    label: "Work Experience"
    description: "My work experiences!"
    folder: "client/src/content/work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Job Title", name: "job-title", widget: "string" }
      - {
          label: "Image Thumbnail",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Timeframe", name: "timeframe", widget: "string" }
      - {
          label: "Live Website URL",
          name: "website-url",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "projects"
    label: "Personal Projects"
    label_singular: "Personal Project"
    description: "Personal projects!"
    folder: "client/src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Image Thumbnail",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Timeframe", name: "timeframe", widget: "string" }
      - { label: "Repository URL", name: "repo-url", widget: "string" }
      - {
          label: "Live Website URL",
          name: "website-url",
          widget: "string",
          required: false,
        }
      - { label: "Technologies Used", name: "technologies", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "involvement"
    label: "Involvement"
    label_singular: "Extracurricular"
    description: "Clubs and extracurriculars!"
    folder: "client/src/content/involvement"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Activity", name: "activity", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - {
          label: "Image Thumbnail",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Timeframe", name: "timeframe", widget: "string" }
      - {
          label: "Live Website URL",
          name: "website-url",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
