# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # pushes frontend code to gh-pages branch
  client-integration:
    name: integrate-client
    runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./client

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Building the website
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: build site
        run: |
          npm ci
          npm run export
          echo "# Hi!" > out/README.md
          echo "You're currently looking at the build artifacts of my website. To check out the code, switch over to the Main branch!" >> out/README.md
          echo "#### Note - This message was automatically generated." >> out/README.md
        working-directory: ./client
        
      # push build artifacts to gh-pages branch
#       - uses: s0/git-publish-subdir-action@develop
#         env:
#           REPO: self
#           BRANCH: gh-pages
#           FOLDER: build
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
