# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # pushes frontend code to gh-pages branch
  client-integration:
    name: integrate-client
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: cd client

      # Building the website
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run export
      - run: echo "# Hi!" > out/README.md
      - run: echo "You're currently looking at the build artifacts of my website. To check out the code, switch over to the Main branch!" >> out/README.md
      - run: echo "#### Note - This message was automatically generated." >> out/README.md
