# Builds and pushes frontend to gh-pages branch
# Pushes backend to server branch

name: Merge-CMS

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # pushes backend code to server branch
  server-integration:
    name: merge-cms
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: "cms_updates"
          commit_message_template: "[Automated] Merged {source_ref} into target {target_branch}"
